	@IMPORT update_ui_border_masks
	@IMPORT newframe_vblank

	@IMPORT update_sgb_palette

	@IMPORT OAM_W
	@IMPORT OAM_R

	@IMPORT gbc_chr_update
	@IMPORT GFX_init
	@IMPORT GFX_reset
	@IMPORT FF40_R
	@IMPORT FF40_W
	@IMPORT FF41_R
	@IMPORT FF41_W
	@IMPORT FF42_R
	@IMPORT FF42_W
	@IMPORT FF43_R
	@IMPORT FF43_W
	@IMPORT FF44_R
	@IMPORT FF44_W
	@IMPORT FF45_R
	@IMPORT FF45_W
	@IMPORT FF46_W
	@IMPORT FF47_R
	@IMPORT FF47_W
	@IMPORT FF48_R
	@IMPORT FF48_W
	@IMPORT FF49_R
	@IMPORT FF49_W
	@IMPORT FF4A_R
	@IMPORT FF4A_W
	@IMPORT FF4B_R
	@IMPORT FF4B_W
	@IMPORT FF4F_W
	@IMPORT FF4F_R
	@IMPORT FF68_R
	@IMPORT FF69_R
	@IMPORT FF6A_R
	@IMPORT FF6B_R
	@IMPORT FF68_W
	@IMPORT FF69_W
	@IMPORT FF6A_W
	@IMPORT FF6B_W
	@IMPORT vram_W
	@IMPORT vram_W2
@	IMPORT agb_nt_map
@	IMPORT VRAM_chr
@	IMPORT vram_map
  @IMPORT gbc_palette
	@IMPORT debug_
@	IMPORT map_palette
	@IMPORT newframe
	@IMPORT lcdstate
@	IMPORT writeBG
@	IMPORT oambuffer
	@IMPORT resetlcdregs
	@.end
